- hosts: a2hosting
  become: true
  tasks:
    - name: Install Aptitude Package Manager for Ansible
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install UFW Firewall
      apt:
        pkg:
          - ufw
        state: latest
        update_cache: true
      tags: ["setup"]

    - name: Install curl, wget, jq, nano
      apt:
        pkg:
          - curl
          - nano
          - jq
          - wget
        state: latest
        update_cache: true
      tags: ["setup"]

    - name: Install git, bash-completion
      apt:
        pkg:
          - bash-completion
          - git
        state: latest
        update_cache: true
      tags: ["setup"]

