- hosts: a2hosting
  become: true

  tasks:
    - name: Create required Nginx dirs
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        owner: root
        mode: 0755
      loop:
        - { "path": "/etc/nginx/conf.d" }
        - { "path": "/etc/nginx/conf.d/streams" }
        - { "path": "/etc/nginx/modules-enabled" }
        - { "path": "/etc/nginx/modules-available" }
        - { "path": "/etc/nginx/open-telemetry" }
        - { "path": "/etc/apache2" }

    - name: Copy Otel config for Nginx Open Telemetry
      ansible.builtin.copy:
        src: /home/murph/workspace/nginx-otel/opentelemetry_module.conf
        dest: /etc/nginx/open-telemetry
        force: true
        backup: true
        owner: root
        mode: 0755

    - name: Copy Otel Module for Nginx Open Telemetry
      ansible.builtin.copy:
        src: /home/murph/opentelemetry-webserver-sdk/WebServerModule/Nginx/1.22.0/ngx_http_opentelemetry_module.so
        dest: /usr/lib/nginx/modules
        force: true
        backup: true
        owner: root
        mode: 0755

    - name: Copy Nginx config
      ansible.builtin.copy:
        src: /home/murph/workspace/nginx/nginx.conf
        dest: /etc/nginx
        force: true
        backup: true
        owner: root
        mode: 0755

    # - name: Copy Nginx configs
    #   ansible.builtin.copy:
    #     src: /home/murph/workspace/nginx/conf.d/
    #     dest: /etc/nginx/conf.d/
    #     force: true
    #     backup: true
    #     owner: root
    #     mode: 0755

    - name: Copy Nginx Module Configs
      ansible.builtin.copy:
        src: /home/murph/workspace/nginx/modules-available/
        dest: /etc/nginx/modules-enabled/
        force: true
        owner: root
        mode: 0755

    # - name: Copy Naxsi Rules
    #   ansible.builtin.copy:
    #     src: /home/murph/workspace/nginx/naxsi/naxsi.rules
    #     dest: /etc/nginx
    #     force: true
    #     owner: root
    #     mode: 0755

    # - name: Copy Nginx Service
    #   ansible.builtin.copy:
    #     src: /home/murph/workspace/nginx/nginx.service
    #     dest: /etc/systemd/system
    #     force: false
    #     backup: true
    #     owner: root
    #     mode: 0755

    - name: Copy GeoIp2 Config
      ansible.builtin.copy:
        src: /home/murph/workspace/nginx/GeoIP.conf
        dest: /etc/GeoIP.conf
        force: true
        backup: true
        owner: root
        mode: 0755

    - name: Update GeoIP2
      become: true
      shell: sudo geoipupdate

    - name: Ensure cronjob for MaxMind GeoIp Update
      ansible.builtin.cron:
        name: "check dirs"
        minute: "0"
        hour: "1,12"
        weekday: "1,3"
        job: "/usr/local/bin/geoipupdate"

    - name: Enable service Nginx and ensure it is not masked
      ansible.builtin.systemd:
        name: nginx
        enabled: true
        masked: no

    - name: Just force systemd to reread configs (2.4 and above)
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Remove Apache because it also uses port 80
      apt:
        pkg:
          - apache2
          - apache2-bin
          - apache2-data
          - apache2-doc
        state: absent
        purge: true
        update_cache: true

    - name: Make sure Nginx service unit is running
      ansible.builtin.systemd:
        daemon_reload: true
        state: started
        name: nginx

    - name: Restart Nginx service
      ansible.builtin.systemd:
        state: restarted
        name: nginx

