- hosts: a2hosting
  become: true
  tasks:

    - name: Copy SSHD config
      ansible.builtin.copy:
        src: /home/murph/workspace/configs/server_setup_configs/prod_sshd_config
        dest: /etc/ssh/sshd_config
        force: true
        backup: true
        owner: root
        mode: 0644


    - name: Copy Sudoers config
      ansible.builtin.copy:
        src: /home/murph/workspace/configs/server_setup_configs/sudoers
        dest: /etc/sudoers
        force: true
        backup: true
        owner: root
        mode: 0440

    - name: Restart to enable sudo for Docker - can also logout I think, but rebooting by choice
      become: true
      shell: sudo reboot