- hosts: a2hosting
  become: true
  vars:
    frp_version: 0.47.0
    frp_folder: "frp_{{ frp_version }}"
    frp_install_dir: "/opt/{{ frp_folder }}"

  tasks:
    - name: Add Crowdsec Repo's
      become: true
      shell: curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | sudo bash
      args:
        chdir: /home/devops/
        
    
    - name: Install Crowdsec and Bouncer Dependencies
      ansible.builtin.apt:
        pkg:
          - crowdsec
          - lua5.1 
          - libnginx-mod-http-lua 
          - luarocks 
          - gettext-base 
          - lua-cjson
        state: latest
        update_cache: true

    - name: Install Crowdsec Bouncers
      ansible.builtin.apt:
        pkg:
          - crowdsec-firewall-bouncer-iptables
          - crowdsec-nginx-bouncer
        state: latest
        update_cache: true

    - name: Restart Crowdsec service
      ansible.builtin.systemd:
        daemon_reload: true
        state: restarted
        name: crowdsec
        
    - name: Restart Crowsec Firewall Bouncer
      ansible.builtin.systemd:
        daemon_reload: true
        state: restarted
        name: crowdsec-firewall-bouncer

    - name: Restart Nginx service
      ansible.builtin.systemd:
        daemon_reload: true
        state: restarted
        name: nginx

    - name: Setup and Start Crowdsec Local Metrics Dashboard
      become: true
      shell: |
        sudo cscli dashboard setup --yes --password "{{ crowdsec_metabase_password }}"

    - name: Setup and Start Crowdsec Local Metrics Dashboard
      become: true
      shell: |
        docker update --restart=always crowdsec-metabase
    