- hosts: a2hosting
  become: true
  vars_prompt:
  - name: user
    prompt: What is your username?
    private: false
  - name: frp_type
    prompt: What FRP type (Server = frps / Client = frpc)
    private: false
    
  vars:
    frp_folder: "frp"
    frp_install_dir: "/opt/{{ frp_folder }}"

  tasks:
    - name: Copy FRP Proxy Service
      ansible.builtin.copy:
        src: /home/murph/workspace/configs/frp/frps.service
        dest: /etc/systemd/system/
        force: true
        owner: root
        mode: 0755

    - name: Copy FRP Proxy Config
      ansible.builtin.copy:
        src: /home/murph/workspace/configs/frp/frps.toml
        dest: "{{ frp_install_dir }}"
        force: true
        backup: true
        owner: root
        mode: 0755

    - name: Enable service FRP Proxy and ensure it is not masked
      ansible.builtin.systemd:
        name: "{{ frp_type }}"
        enabled: true
        masked: no

    - name: Just force systemd to reread configs
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Make sure FRP Proxy service unit is running
      ansible.builtin.systemd:
        daemon_reload: true
        state: restarted
        name: "{{ frp_type }}"
