- hosts: a2hosting,localhost
  become: true
  vars:
    domains:
      - dev.blog.fullstackindie.net
      - dev.critter.fullstackindie.net
      - dev.identity.fullstackindie.net
      - dev.gateway.fullstackindie.net

  tasks:
    - name: Install certbot python package
      ansible.builtin.pip:
        name: certbot
        virtualenv: /opt/certbot/
        state: latest

    - name: Install certbot-nginx python package
      ansible.builtin.pip:
        name: certbot-nginx
        virtualenv: /opt/certbot/
        state: latest

    - name: Create symlink for certbot
      file:
        src: /opt/certbot/bin/certbot
        dest: /usr/bin/certbot
        state: link
      become: yes

    - name: Register certbot
      become: true
      shell: |
        certbot -n register --agree-tos --email fortheone.dev@gmail.com
        touch /etc/letsencrypt/.registered
      args:
        creates: /etc/letsencrypt/.registered

    - name: Setup cronjob for renewal
      become: true
      cron:
        name: certbot-renewal
        job: "/bin/bash -lc '/usr/bin/certbot -q renew'"
        minute: "0"
        hour: "14"

    - name: "Get certificates for Copied Nginx Configs and Known/Common Websites with Registered Domains"
      become: true
      command: "certbot -n --nginx certonly -d {{ item }}"
      args:
        creates: "/etc/letsencrypt/live/{{ item }}"
      ignore_errors: true
      loop: "{{ domains }}"

    - name: Make sure Nginx service unit is running
      ansible.builtin.systemd:
        daemon_reload: true
        state: started
        name: nginx

    - name: Restart Nginx service
      ansible.builtin.systemd:
        state: restarted
        name: nginx
