- hosts: a2hosting
  become: true

  tasks:
    - name: Delete unnecessary tar.gz folders
      shell: sudo rm -r {{ item.path }}
      loop:
        - { path: "/home/devops/nginx_compiled/*.gz" }
        - { path: "/usr/local/nginx/modules/*.so.old" }
        - { path: "/usr/lib/nginx/modules/*.so.old" }
        - { path: "/opt/frp_0.47.0/*.gz" }
        - { path: "/opt/frp_0.47.0/*.ini" }
        - { path: "/opt/frp_0.47.0/frp_0.47.0_linux_amd64/*.ini.*" }
        - { path: "/etc/nginx/nginx.conf.*" }
        - { path: "/etc/nginx/conf.d/streams/*.conf.*" }
        - { path: "/etc/nginx/conf.d/*.conf.*" }
        - { path: "/etc/nginx/modules-enabled/*.conf.*" }
        - { path: "/etc/nginx/open-telemetry/*.toml.*" }
        - { path: "/home/devops/workspace/compose/*.yml.*" }