- hosts: a2hosting,localhost
  become: true
  tasks:

    - name: Copy SSHD config
      ansible.builtin.copy:
        src: /home/murph/workspace/configs/server_setup_configs/prod_sshd_config
        dest: /etc/ssh/sshd_config
        force: true
        backup: true
        owner: root
        mode: 0644


        
    - name: Restart SSH
      become: true
      command: 'systemctl restart ssh'

