- hosts: a2hosting
  become: true

  tasks:
    - name: Install Doppler's neccessary Packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates 
          - curl 
          - gnupg
        state: latest
        update_cache: true

    - name: Add Doppler GPG key 
      become: true
      shell: curl -sLf --retry 3 --tlsv1.2 --proto "=https" 'https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key' | sudo gpg --dearmor -o /usr/share/keyrings/doppler-archive-keyring.gpg
   
    - name: Add Doppler's apt repo
      become: true
      shell: echo "deb [signed-by=/usr/share/keyrings/doppler-archive-keyring.gpg] https://packages.doppler.com/public/cli/deb/debian any-version main" | sudo tee /etc/apt/sources.list.d/doppler-cli.list

    - name: Install Doppler's neccessary Packages
      apt:
        pkg:
          - doppler
        state: latest
        update_cache: true
