- hosts: a2hosting,localhost
  become: true
  vars_prompt:
    - name: user
      prompt: What is your username?
      private: false
      
  tasks:

    - name: Uninstall Crowdsec and Bouncers for clean install
      ansible.builtin.apt:
        pkg:
          - crowdsec-firewall-bouncer-iptables
          - crowdsec-firewall-bouncer-nftables
          - crowdsec-nginx-bouncer
        state: absent
        update_cache: true

    # - name: Add Crowdsec Repo's
    #   become: true
    #   shell: curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | sudo bash
    #   args:
    #     chdir: /home/{{ user }}/
        

    - name: Install Crowdsec Firewall Bouncer
      ansible.builtin.apt:
        pkg:
          - crowdsec-firewall-bouncer-iptables
        state: latest
        update_cache: true

    - name: Restart Crowsec Firewall Bouncer
      ansible.builtin.systemd:
        daemon_reload: true
        state: restarted
        name: crowdsec-firewall-bouncer