- hosts: a2hosting,localhost
  become: true
  vars_prompt:
    - name: user
      prompt: What is your username?
      private: false
      
  tasks:

    - name: Uninstall Crowdsec and Bouncers for clean install
      ansible.builtin.apt:
        pkg:
          - crowdsec
        state: absent
        update_cache: true

    - name: Add Crowdsec Repo's
      become: true
      shell: curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | sudo bash
      args:
        chdir: /home/{{ user }}/
        
    - name: Install Crowdsec
      ansible.builtin.apt:
        pkg:
          - crowdsec
        state: latest
        update_cache: true


    - name: Setup and Start Crowdsec Local Metrics Dashboard
      become: true
      shell: |
        if [ "$(docker ps -q -f name=crowdsec-metabase)" ]; then
          exit 0
        fi
        cscli dashboard setup --yes --password "{{ crowdsec_metabase_password }}"
      register: crowdsec_container_exists

    - name: Update Crowdsec Docker Container to Restart always
      become: true
      shell: |
        docker update --restart=always crowdsec-metabase
      when: crowdsec_container_exists.changed

    - name: Installing Crowdsec Scenarios via Collections
      become: true
      shell: "{{ item }}"
      with_items:
        - cscli collections install crowdsecurity/linux
        - cscli collections install crowdsecurity/linux-lpe
        - cscli collections install crowdsecurity/sshd
        - cscli collections install crowdsecurity/whitelist-good-actors
        - cscli collections install crowdsecurity/base-http-scenarios
        - cscli collections install crowdsecurity/wordpress
        - cscli collections install crowdsecurity/endlessh
        - cscli collections install crowdsecurity/http-cve
        - cscli collections install crowdsecurity/iptables
        - cscli collections install crowdsecurity/nginx
        - cscli collections install openappsec/openappsec
        - cscli collections install crowdsecurity/pgsql

    - name: Installing Crowdsec Parsers
      become: true
      shell: "{{ item }}"
      with_items:
        - cscli parsers install crowdsecurity/cri-logs
        - cscli parsers install crowdsecurity/dateparse-enrich
#cscli collections install LePresidente/grafana

    - name: Enable Crowdsec Bash Completion
      become: true
      shell: cscli completion bash | tee /etc/bash_completion.d/cscli


    - name: Restart Crowdsec service
      ansible.builtin.systemd:
        daemon_reload: true
        state: restarted
        name: crowdsec

