- hosts: a2hosting,localhost
  become: true
  vars:
    user: murph
  tasks:
    - name: Copy Crowdsec Nginx Bouncer configuration for Captcha
      ansible.builtin.copy:
        src: /home/{{ user }}/workspace/crowdsec/crowdsec-nginx-bouncer.conf
        dest: /etc/crowdsec/bouncers/crowdsec-nginx-bouncer.conf
        force: true
        backup: true
        owner: root
        mode: 0755

    - name: Copy Crowdsec Profile for Captcha
      ansible.builtin.copy:
        src: /home/{{ user }}/workspace/crowdsec/profiles.yaml
        dest: /etc/crowdsec/profiles.yaml
        force: true
        backup: true
        owner: root
        mode: 0755


    - name: Restart Crowdsec service
      ansible.builtin.systemd:
        daemon_reload: true
        state: restarted
        name: crowdsec
        
    - name: Restart Crowsec Firewall Bouncer
      ansible.builtin.systemd:
        daemon_reload: true
        state: restarted
        name: crowdsec-firewall-bouncer

    - name: Restart Nginx service
      become: true
      ansible.builtin.systemd:
        state: reloaded
        name: crowdsec
