- hosts: a2hosting,localhost
  become: true
  vars:
    nginx_modules_path: "/usr/lib/nginx/modules"
    
  vars_prompt:
    - name: user
      prompt: What is your Ansible Control Node username?
      private: false

  tasks:
    - name: Create required Nginx dirs
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        owner: root
        mode: 0755
      loop:
        - { "path": "/etc/nginx/conf.d" }
        - { "path": "/etc/nginx/conf.d/streams" }
        - { "path": "/etc/nginx/modules-enabled" }
        - { "path": "/etc/nginx/modules-available" }

    - name: Copy Nginx config
      ansible.builtin.copy:
        src: /home/{{ user }}/workspace/nginx/nginx.conf
        dest: /etc/nginx
        force: true
        backup: true
        owner: root
        mode: 0755

    - name: Copy Nginx configs
      ansible.builtin.copy:
        src: /home/{{ user }}/workspace/nginx/conf.d
        dest: /etc/nginx/
        force: true
        backup: true
        owner: root
        mode: 0755

    - name: Copy Nginx Module Configs
      ansible.builtin.copy:
        src: /home/{{ user }}/workspace/nginx/modules-available/
        dest: /etc/nginx/modules-enabled/
        force: true
        owner: root
        mode: 0755

    # - name: Copy Nginx Service
    #   become: true
    #   ansible.builtin.copy:
    #     src: /home/{{ user }}/workspace/nginx/nginx.service
    #     dest: /etc/systemd/system
    #     force: false
    #     backup: true
    #     owner: root
    #     mode: 0755

    - name: Copy GeoIp2 Config
      become: true
      ansible.builtin.copy:
        src: /home/{{ user }}/workspace/nginx/GeoIP.conf
        dest: /etc/GeoIP.conf
        force: true
        backup: true
        owner: root
        mode: 0755

    - name: Update GeoIP2
      become: true
      shell: geoipupdate

    - name: Ensure cronjob for MaxMind GeoIp Update
      become: true
      ansible.builtin.cron:
        name: "check dirs"
        minute: "0"
        hour: "1,12"
        weekday: "1,3"
        job: "/usr/local/bin/geoipupdate"

    - name: Enable service Nginx and ensure it is not masked
      become: true
      ansible.builtin.systemd:
        name: nginx
        enabled: true
        masked: no

    - name: Just force systemd to reread configs
      become: true
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Restart Nginx service
      become: true
      ansible.builtin.systemd:
        state: reloaded
        name: nginx 
