- hosts: a2hosting
  become: true
  tasks:

    - name: Copy Otel config for Nginx Open Telemetry
      ansible.builtin.copy:
        src: /home/murph/workspace/nginx/otelcollector/otel_config.toml
        dest: /etc/nginx/open-telemetry
        force: true
        backup: false
        owner: root
        mode: 0755

    - name: Copy Otel Module for Nginx Open Telemetry
      ansible.builtin.copy:
        src: /home/murph/workspace/nginx/otelcollector/otel_ngx_module.so
        dest: /usr/local/nginx/modules
        force: true
        backup: false
        owner: root
        mode: 0755

    - name: Copy Nginx config
      ansible.builtin.copy:
        src: /home/murph/workspace/nginx/nginx.conf
        dest: /etc/nginx
        force: true
        backup: false
        owner: root
        mode: 0755

    - name: Copy Nginx configs
      ansible.builtin.copy:
        src: /home/murph/workspace/nginx/conf.d/
        dest: /etc/nginx/conf.d/
        force: true
        backup: false
        owner: root
        mode: 0755

    - name: Copy Portfolio configs
      ansible.builtin.copy:
        src: /home/murph/workspace/nginx/conf.d/portfolio/challenges/
        dest: /etc/nginx/conf.d/portfolio/challenges/
        force: true
        backup: false
        owner: root
        mode: 0755

    - name: Copy Nginx Module Configs
      ansible.builtin.copy:
        src: /home/murph/workspace/nginx/modules-available/
        dest: /etc/nginx/modules-enabled/
        force: true
        owner: root
        mode: 0755

    - name: Copy Naxsi Rules
      ansible.builtin.copy:
        src: /home/murph/workspace/nginx/naxsi/naxsi.rules
        dest: /etc/nginx
        force: true
        owner: root
        mode: 0755


    - name: Copy GeoIp2 Config
      ansible.builtin.copy:
        src: /home/murph/workspace/nginx/GeoIP.conf
        dest: /etc/GeoIP.conf
        force: true
        backup: false
        owner: root
        mode: 0755

    - name: Update GeoIP2
      become: true
      shell: sudo geoipupdate

    - name: Ensure cronjob for MaxMind GeoIp Update
      ansible.builtin.cron:
        name: "check dirs"
        minute: "0"
        hour: "1,12"
        weekday: "1,3"
        job: "/usr/local/bin/geoipupdate"

    - name: Enable service Nginx and ensure it is not masked
      ansible.builtin.systemd:
        name: nginx
        enabled: true
        masked: no

    - name: Just force systemd to reread configs (2.4 and above)
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Setup cronjob for renewal
      cron:
        name: certbot-renewal
        job: "/bin/bash -lc '/usr/local/bin/certbot -q renew'"
        minute: "0"
        hour: "14"

    - name: Make sure Nginx service unit is running
      ansible.builtin.systemd:
        daemon_reload: true
        state: started
        name: nginx

    - name: Restart Nginx service
      ansible.builtin.systemd:
        state: restarted
        name: nginx