- hosts: a2hosting
  become: true
  vars_prompt:
    - name: user
      prompt: What is your username?
      private: false
  vars:
    compose_name: garnet
    compose_network: telemetry
    compose_volume: garnet
    compose_path: /home/{{ user }}/workspace/compose/{{ compose_name }}

  tasks:
    - name: Create required Garnet dirs
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ user }}"
        mode: 0755
      with_items:
        - { path: "{{ compose_path }}" }

    - name: Copy Docker Compose
      ansible.builtin.copy:
        src: /home/murph/workspace/compose/garnet/garnet.yml
        dest: "{{ compose_path }}/"
        force: true
        backup: true
        owner: "{{ user }}"
        mode: 0755

    - name: Log into private registry and force re-authorization
      community.docker.docker_login:
        registry_url: https://index.docker.io/v2
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
        reauthorize: true

    - name: Create a Docker network
      community.docker.docker_network:
        name: "{{ compose_network }}"
        state: present

    - name: Remove a volume
      community.docker.docker_volume:
        name: "{{ compose_volume }}"
        state: present

    - name: Login into Docker
      shell: |
        docker login --username {{ docker_username }} --password {{ docker_password  }}

    - name: Stop exisiting Docker Compose
      shell: |
        docker compose -f ./{{ compose_name }}.yml down
      args:
        chdir: "{{ compose_path }}"

    - name: Start Docker Compose
      shell: |
        export REDIS_PASSWORD={{ redis_password }}
        docker compose -f ./{{ compose_name }}.yml up -d
      args:
        chdir:
          "{{ compose_path }}"
